url: https://y7kim.github.io
baseurl: ""

# Site settings
title: Lukas Hoffman
email: your-email@domain.com
description: "The official webpage of Lukas Hoffman."

# Build settings
markdown: kramdown
permalink: pretty
